import Head from "next/head"
import { Center, Box, Spacer, Button, Grid } from "@chakra-ui/react"
import { iUserEmail } from "@/types/user.interface"
import Main from "./home"

export default function Home({ email }: iUserEmail) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Center>
				<Main email={email} />
			</Center>
		</>
	)
}
